# Test global information
entrypoint: welcome
variables:
  title: FlexEval
  authors: Cédric Fayet

# Administration configuration
admin:
  entrypoint:
    mod: admin_panel
    password: bflzefinlh67s
    variables:
      subtitle: Admin Panel
  mods:
  - mod: export_bdd
    variables:
      subtitle: Download BDD
      subdescription: Download the database in CSV or SQLite format.

# Structure of the evaluation
stages:
  # First steps
  welcome:
    type: page:visitor
    template: welcome.tpl
    next: choiceOneOFTwoTests

  choiceOneOFTwoTests:
    type: page:user
    template: choiceBetweenTwoTests.tpl
    next:
      testMOS: test_mos
      testAB: test_ab

  # AB Test configuration
  test_ab:
    type: test
    template: ab.tpl
    next: end_test
    nb_steps: 5
    nb_step_intro: 2
    transaction_timeout_seconds: 600
    variables:
      subtitle: Test AB

  # MOS Test configuration
  test_mos:
    type: test
    template: mos.tpl
    next: end_test
    nb_steps: 5
    nb_step_intro: 2
    transaction_timeout_seconds: 600
    variables:
      subtitle: Test MOS

  # End of the test
  end_test:
    type: page:user
    template: end.tpl
